// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM0niocF-Jryla_8TDnThLdqpe_LjknzY',
    appId: '1:816991407076:web:6a1297eb82a361d4dcd5f1',
    messagingSenderId: '816991407076',
    projectId: 'myfirstflutter-b8fe5',
    authDomain: 'myfirstflutter-b8fe5.firebaseapp.com',
    storageBucket: 'myfirstflutter-b8fe5.appspot.com',
    measurementId: 'G-X64Q16T95B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUmpQSz5QCqgvFctJ8CUwpYGZj5uvfNN0',
    appId: '1:816991407076:android:ec3232d91d7a52f9dcd5f1',
    messagingSenderId: '816991407076',
    projectId: 'myfirstflutter-b8fe5',
    storageBucket: 'myfirstflutter-b8fe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7sHL7rF3OSGKnXHrBdRI1N2H4UmOafX0',
    appId: '1:816991407076:ios:caad73947930aa09dcd5f1',
    messagingSenderId: '816991407076',
    projectId: 'myfirstflutter-b8fe5',
    storageBucket: 'myfirstflutter-b8fe5.appspot.com',
    iosClientId: '816991407076-svh1m7lbnobh8acuj4ruu9tl250n94q0.apps.googleusercontent.com',
    iosBundleId: 'quit',
  );
}
